### ISSUE TITLE
VkFFT fails on GPU

### ISSUE THREAD

**Issue by inducer** [inducer/sumpy#127]
Gitlab CI run: https://gitlab.tiker.net/inducer/sumpy/-/jobs/439559

@isuruf, could you take a look?

**Comment by isuruf** [comment]
The error is weird. `pyopencl._cl.RuntimeError: clGetEventProfilingInfo failed: PROFILING_INFO_NOT_AVAILABLE`
This error should be reproducible and yet I can't reproduce locally.

**Comment by inducer** [comment]
Did you run on the pocl+cuda device?

**Comment by isuruf** [comment]
Yes, tried `pocl:cuda`, `pocl:pthread` and `nvidia` all of which passes the test.

**Comment by isuruf** [comment]
Nvm, I can reproduce
