### ISSUE TITLE
e2p for H2DLocalExpansion evaluates Bessel functions redundantly in test_p2e2p

### ISSUE THREAD

**Issue by inducer** [inducer/sumpy#61]
(This happens in connection with the second output, a `DirectionalSourceDerivative`.)

cc @isuruf

**Comment by isuruf** [comment]
I'm not sure I understand what the issue is. Can you explain?

**Comment by inducer** [comment]
Sure! `test_p2e2p` computes two "target kernels", one the plain kernel, the other a source derivative. Both involve evaluation of Bessel functions of different orders, but with the same argument. (The base kernel needs `J3` at most, the derivative up to `J5`.) They both take the same argument, but the CSE processing isn't smart enough to recognize that, leading to redundant evaluation of the Bessel function.
